# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

permalink: /:title.html
paginate: 5
gems:
  - jekyll-paginate
  - jekyll-last-modified-at
port: 3000
safe: true


# edit here to achieve your personal greatness
url: xiaoxia.link
title: Xiao Xia
author: Xiao Xia
description: Xiao Xia's personal website
avatar: profile.png
email: judexia@buaa.edu.cn
linkedin: judexia
google_analytics: UA-109315918-1

#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
#github: biomadeira/sustain # username
#twitter: username

timezone: America/New_York


# needed for travis-ci build
exclude: [vendor]
